### ISSUE TITLE
Замечания к лабораторной

### ISSUE THREAD

**Issue by rredbird66** [Egorxd/lab2pzrl#1]
Всё хорошо, но, вроде, по требованиям необходимо использовать в Makefile переменные. Добавьте.

**Comment by Egorxd** [comment]
> Всё хорошо, но, вроде, по требованиям необходимо использовать в Makefile переменные. Добавьте.

Исправил

**Comment by rredbird66** [comment]
Ну можно было и нормально, с пользой и смыслом добавить, а не просто для отписки. Имя собираемого исполняемого файла сделать переменной, или флаги компиляции. Но да ладно. Формально переменная есть.
Лабораторная работа 2 зачтена.
